# Generated by Django 4.1.6 on 2023-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project", name="code", field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="project", name="live", field=models.URLField(null=True),
        ),
    ]
